### PR TITLE
Rename SQL-to-REST to SQL-to-OpenAPI

### PR DESCRIPTION
**Pull request by simonplend**
These changes correspond with the renaming changes made in pull request https://github.com/platformatic/platformatic/pull/342.

### CODE REVIEW

**Review by marcopiraccini — APPROVED** [review]
lgtm, but you have to sign the DCO :)

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by simonplend** [comment]
> lgtm, but you have to sign the DCO :)

@marcopiraccini Our docs [aren't super clear on how to do that](https://github.com/platformatic/platformatic/blob/main/CONTRIBUTING.md#developer-contribution-of-origin). Do I need to [sign off the commits retroactively](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md#how-to-add-sign-offs-retroactively) and then force-push this branch?

**Comment by simonplend** [comment]
I've just seen that the DCO action contains the details of what to do: https://github.com/platformatic/oss/pull/42/checks?check_run_id=9562279946. It's a shame it doesn't comment directly on the PR too.

**Pull request merged**
